[package]
name = "linux-stat"
version = "0.0.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["std"]
std = ["linux-syscalls/std"]
linux_4_11 = []

[target.'cfg(target_os = "linux")'.dev-dependencies]
libc = { version = "0.2.144", default-features = false }

[dependencies]
linux-syscalls = { version = "0.1.1", default-features = false }
